apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: {{.Env.SERVICE_APP_IMAGE_NAME}}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/Config
      volumes:
      - name: config-volume 
        configMap: 
          name: demo-app-config
